spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
# noinspection undefined
greeting-service:
  greeting: "Hello"
  default-value: "World"